---
title: "ggplot_1"
author: "Matthew Parker"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(hexbin)
```


## Create weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```


## Create a ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Alternate way of making this plot

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

saving initial plots. mostly not used by Jeff.

```{r}
scatterplot = weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

scatterplot
```

adding color

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4)
```

why do 'aes' positions matter?

first
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) + 
  geom_smooth(se = FALSE)
```

vs
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE)
```

facet!

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE) + 
  facet_grid(~ name)
```

this is fine, but not interesting.

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = 0.5) + 
  geom_smooth(size = 2, se = FALSE)
```


## Some extra stuff

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_smooth(size = 2, se = FALSE)
```

2d density

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_bin2d()
```


## More kinds of plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram() + 
  facet_grid(~ name)
```

density plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = 0.3)
```

boxplot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```

violin plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```

ridge plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) + 
  ggridges::geom_density_ridges()
```


## saving a plot

```{r}
ggp_ridge_temp = weather_df %>% 
  ggplot(aes(x = tmax, y = name)) + 
  ggridges::geom_density_ridges()

ggsave("ggplot_temp_ridge.pdf", ggp_ridge_temp)
```

Figure width
```{r, fig.width=6}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE) 
```

```{r, fig.width=12}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE) 
```

